[package]
publish = false
name = "wasmer-jni"
version = "0.3.0"
authors = ["Ivan Enderlin <ivan.enderlin@hoa-project.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmer = "2.0.0"
wasmer-compiler-cranelift = "2.0.0"
wasmer-engine-universal = "2.0.0"
jni = "0.19"
